apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster-client-service
spec:
  selector:
    etcd_cluster: etcd-cluster
    app: etcd
  ports:
  - name: 2379-tcp
    protocol: TCP
    port: 2379 
    nodePort: 32379
  type: NodePort
